-- NeetCode 150: the fixed list of problems you work through.
-- Source: NeetCode's own problem data (github.com/neetcode-gh/leetcode, .problemSiteData.json),
-- entries flagged "neetcode150", in NeetCode roadmap order. Links go to LeetCode.

CREATE TABLE catalog_problems (
    id              SMALLINT     PRIMARY KEY,          -- 1..150, roadmap order
    category        VARCHAR(40)  NOT NULL,
    category_order  SMALLINT     NOT NULL,             -- 1 = Arrays & Hashing ... 18 = Bit Manipulation
    name            VARCHAR(200) NOT NULL,
    difficulty      VARCHAR(6)   NOT NULL CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    url             VARCHAR(500) NOT NULL
);
CREATE UNIQUE INDEX catalog_problems_name_unique ON catalog_problems (lower(name));

INSERT INTO catalog_problems (id, category, category_order, name, difficulty, url) VALUES
    (1, 'Arrays & Hashing', 1, 'Contains Duplicate', 'EASY', 'https://leetcode.com/problems/contains-duplicate/'),
    (2, 'Arrays & Hashing', 1, 'Valid Anagram', 'EASY', 'https://leetcode.com/problems/valid-anagram/'),
    (3, 'Arrays & Hashing', 1, 'Two Sum', 'EASY', 'https://leetcode.com/problems/two-sum/'),
    (4, 'Arrays & Hashing', 1, 'Group Anagrams', 'MEDIUM', 'https://leetcode.com/problems/group-anagrams/'),
    (5, 'Arrays & Hashing', 1, 'Top K Frequent Elements', 'MEDIUM', 'https://leetcode.com/problems/top-k-frequent-elements/'),
    (6, 'Arrays & Hashing', 1, 'Product of Array Except Self', 'MEDIUM', 'https://leetcode.com/problems/product-of-array-except-self/'),
    (7, 'Arrays & Hashing', 1, 'Valid Sudoku', 'MEDIUM', 'https://leetcode.com/problems/valid-sudoku/'),
    (8, 'Arrays & Hashing', 1, 'Encode and Decode Strings', 'MEDIUM', 'https://leetcode.com/problems/encode-and-decode-strings/'),
    (9, 'Arrays & Hashing', 1, 'Longest Consecutive Sequence', 'MEDIUM', 'https://leetcode.com/problems/longest-consecutive-sequence/'),
    (10, 'Two Pointers', 2, 'Valid Palindrome', 'EASY', 'https://leetcode.com/problems/valid-palindrome/'),
    (11, 'Two Pointers', 2, 'Two Sum II Input Array Is Sorted', 'MEDIUM', 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/'),
    (12, 'Two Pointers', 2, '3Sum', 'MEDIUM', 'https://leetcode.com/problems/3sum/'),
    (13, 'Two Pointers', 2, 'Container With Most Water', 'MEDIUM', 'https://leetcode.com/problems/container-with-most-water/'),
    (14, 'Two Pointers', 2, 'Trapping Rain Water', 'HARD', 'https://leetcode.com/problems/trapping-rain-water/'),
    (15, 'Sliding Window', 3, 'Best Time to Buy And Sell Stock', 'EASY', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/'),
    (16, 'Sliding Window', 3, 'Longest Substring Without Repeating Characters', 'MEDIUM', 'https://leetcode.com/problems/longest-substring-without-repeating-characters/'),
    (17, 'Sliding Window', 3, 'Longest Repeating Character Replacement', 'MEDIUM', 'https://leetcode.com/problems/longest-repeating-character-replacement/'),
    (18, 'Sliding Window', 3, 'Permutation In String', 'MEDIUM', 'https://leetcode.com/problems/permutation-in-string/'),
    (19, 'Sliding Window', 3, 'Minimum Window Substring', 'HARD', 'https://leetcode.com/problems/minimum-window-substring/'),
    (20, 'Sliding Window', 3, 'Sliding Window Maximum', 'HARD', 'https://leetcode.com/problems/sliding-window-maximum/'),
    (21, 'Stack', 4, 'Valid Parentheses', 'EASY', 'https://leetcode.com/problems/valid-parentheses/'),
    (22, 'Stack', 4, 'Min Stack', 'MEDIUM', 'https://leetcode.com/problems/min-stack/'),
    (23, 'Stack', 4, 'Evaluate Reverse Polish Notation', 'MEDIUM', 'https://leetcode.com/problems/evaluate-reverse-polish-notation/'),
    (24, 'Stack', 4, 'Generate Parentheses', 'MEDIUM', 'https://leetcode.com/problems/generate-parentheses/'),
    (25, 'Stack', 4, 'Daily Temperatures', 'MEDIUM', 'https://leetcode.com/problems/daily-temperatures/'),
    (26, 'Stack', 4, 'Car Fleet', 'MEDIUM', 'https://leetcode.com/problems/car-fleet/'),
    (27, 'Stack', 4, 'Largest Rectangle In Histogram', 'HARD', 'https://leetcode.com/problems/largest-rectangle-in-histogram/'),
    (28, 'Binary Search', 5, 'Binary Search', 'EASY', 'https://leetcode.com/problems/binary-search/'),
    (29, 'Binary Search', 5, 'Search a 2D Matrix', 'MEDIUM', 'https://leetcode.com/problems/search-a-2d-matrix/'),
    (30, 'Binary Search', 5, 'Koko Eating Bananas', 'MEDIUM', 'https://leetcode.com/problems/koko-eating-bananas/'),
    (31, 'Binary Search', 5, 'Find Minimum In Rotated Sorted Array', 'MEDIUM', 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/'),
    (32, 'Binary Search', 5, 'Search In Rotated Sorted Array', 'MEDIUM', 'https://leetcode.com/problems/search-in-rotated-sorted-array/'),
    (33, 'Binary Search', 5, 'Time Based Key Value Store', 'MEDIUM', 'https://leetcode.com/problems/time-based-key-value-store/'),
    (34, 'Binary Search', 5, 'Median of Two Sorted Arrays', 'HARD', 'https://leetcode.com/problems/median-of-two-sorted-arrays/'),
    (35, 'Linked List', 6, 'Reverse Linked List', 'EASY', 'https://leetcode.com/problems/reverse-linked-list/'),
    (36, 'Linked List', 6, 'Merge Two Sorted Lists', 'EASY', 'https://leetcode.com/problems/merge-two-sorted-lists/'),
    (37, 'Linked List', 6, 'Reorder List', 'MEDIUM', 'https://leetcode.com/problems/reorder-list/'),
    (38, 'Linked List', 6, 'Remove Nth Node From End of List', 'MEDIUM', 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/'),
    (39, 'Linked List', 6, 'Copy List With Random Pointer', 'MEDIUM', 'https://leetcode.com/problems/copy-list-with-random-pointer/'),
    (40, 'Linked List', 6, 'Add Two Numbers', 'MEDIUM', 'https://leetcode.com/problems/add-two-numbers/'),
    (41, 'Linked List', 6, 'Linked List Cycle', 'EASY', 'https://leetcode.com/problems/linked-list-cycle/'),
    (42, 'Linked List', 6, 'Find The Duplicate Number', 'MEDIUM', 'https://leetcode.com/problems/find-the-duplicate-number/'),
    (43, 'Linked List', 6, 'LRU Cache', 'MEDIUM', 'https://leetcode.com/problems/lru-cache/'),
    (44, 'Linked List', 6, 'Merge K Sorted Lists', 'HARD', 'https://leetcode.com/problems/merge-k-sorted-lists/'),
    (45, 'Linked List', 6, 'Reverse Nodes In K Group', 'HARD', 'https://leetcode.com/problems/reverse-nodes-in-k-group/'),
    (46, 'Trees', 7, 'Invert Binary Tree', 'EASY', 'https://leetcode.com/problems/invert-binary-tree/'),
    (47, 'Trees', 7, 'Maximum Depth of Binary Tree', 'EASY', 'https://leetcode.com/problems/maximum-depth-of-binary-tree/'),
    (48, 'Trees', 7, 'Diameter of Binary Tree', 'EASY', 'https://leetcode.com/problems/diameter-of-binary-tree/'),
    (49, 'Trees', 7, 'Balanced Binary Tree', 'EASY', 'https://leetcode.com/problems/balanced-binary-tree/'),
    (50, 'Trees', 7, 'Same Tree', 'EASY', 'https://leetcode.com/problems/same-tree/'),
    (51, 'Trees', 7, 'Subtree of Another Tree', 'EASY', 'https://leetcode.com/problems/subtree-of-another-tree/'),
    (52, 'Trees', 7, 'Lowest Common Ancestor of a Binary Search Tree', 'MEDIUM', 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/'),
    (53, 'Trees', 7, 'Binary Tree Level Order Traversal', 'MEDIUM', 'https://leetcode.com/problems/binary-tree-level-order-traversal/'),
    (54, 'Trees', 7, 'Binary Tree Right Side View', 'MEDIUM', 'https://leetcode.com/problems/binary-tree-right-side-view/'),
    (55, 'Trees', 7, 'Count Good Nodes In Binary Tree', 'MEDIUM', 'https://leetcode.com/problems/count-good-nodes-in-binary-tree/'),
    (56, 'Trees', 7, 'Validate Binary Search Tree', 'MEDIUM', 'https://leetcode.com/problems/validate-binary-search-tree/'),
    (57, 'Trees', 7, 'Kth Smallest Element In a Bst', 'MEDIUM', 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/'),
    (58, 'Trees', 7, 'Construct Binary Tree From Preorder And Inorder Traversal', 'MEDIUM', 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/'),
    (59, 'Trees', 7, 'Binary Tree Maximum Path Sum', 'HARD', 'https://leetcode.com/problems/binary-tree-maximum-path-sum/'),
    (60, 'Trees', 7, 'Serialize And Deserialize Binary Tree', 'HARD', 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/'),
    (61, 'Heap / Priority Queue', 8, 'Kth Largest Element In a Stream', 'EASY', 'https://leetcode.com/problems/kth-largest-element-in-a-stream/'),
    (62, 'Heap / Priority Queue', 8, 'Last Stone Weight', 'EASY', 'https://leetcode.com/problems/last-stone-weight/'),
    (63, 'Heap / Priority Queue', 8, 'K Closest Points to Origin', 'MEDIUM', 'https://leetcode.com/problems/k-closest-points-to-origin/'),
    (64, 'Heap / Priority Queue', 8, 'Kth Largest Element In An Array', 'MEDIUM', 'https://leetcode.com/problems/kth-largest-element-in-an-array/'),
    (65, 'Heap / Priority Queue', 8, 'Task Scheduler', 'MEDIUM', 'https://leetcode.com/problems/task-scheduler/'),
    (66, 'Heap / Priority Queue', 8, 'Design Twitter', 'MEDIUM', 'https://leetcode.com/problems/design-twitter/'),
    (67, 'Heap / Priority Queue', 8, 'Find Median From Data Stream', 'HARD', 'https://leetcode.com/problems/find-median-from-data-stream/'),
    (68, 'Backtracking', 9, 'Subsets', 'MEDIUM', 'https://leetcode.com/problems/subsets/'),
    (69, 'Backtracking', 9, 'Combination Sum', 'MEDIUM', 'https://leetcode.com/problems/combination-sum/'),
    (70, 'Backtracking', 9, 'Permutations', 'MEDIUM', 'https://leetcode.com/problems/permutations/'),
    (71, 'Backtracking', 9, 'Subsets II', 'MEDIUM', 'https://leetcode.com/problems/subsets-ii/'),
    (72, 'Backtracking', 9, 'Combination Sum II', 'MEDIUM', 'https://leetcode.com/problems/combination-sum-ii/'),
    (73, 'Backtracking', 9, 'Word Search', 'MEDIUM', 'https://leetcode.com/problems/word-search/'),
    (74, 'Backtracking', 9, 'Palindrome Partitioning', 'MEDIUM', 'https://leetcode.com/problems/palindrome-partitioning/'),
    (75, 'Backtracking', 9, 'Letter Combinations of a Phone Number', 'MEDIUM', 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/'),
    (76, 'Backtracking', 9, 'N Queens', 'HARD', 'https://leetcode.com/problems/n-queens/'),
    (77, 'Tries', 10, 'Implement Trie Prefix Tree', 'MEDIUM', 'https://leetcode.com/problems/implement-trie-prefix-tree/'),
    (78, 'Tries', 10, 'Design Add And Search Words Data Structure', 'MEDIUM', 'https://leetcode.com/problems/design-add-and-search-words-data-structure/'),
    (79, 'Tries', 10, 'Word Search II', 'HARD', 'https://leetcode.com/problems/word-search-ii/'),
    (80, 'Graphs', 11, 'Number of Islands', 'MEDIUM', 'https://leetcode.com/problems/number-of-islands/'),
    (81, 'Graphs', 11, 'Clone Graph', 'MEDIUM', 'https://leetcode.com/problems/clone-graph/'),
    (82, 'Graphs', 11, 'Max Area of Island', 'MEDIUM', 'https://leetcode.com/problems/max-area-of-island/'),
    (83, 'Graphs', 11, 'Pacific Atlantic Water Flow', 'MEDIUM', 'https://leetcode.com/problems/pacific-atlantic-water-flow/'),
    (84, 'Graphs', 11, 'Surrounded Regions', 'MEDIUM', 'https://leetcode.com/problems/surrounded-regions/'),
    (85, 'Graphs', 11, 'Rotting Oranges', 'MEDIUM', 'https://leetcode.com/problems/rotting-oranges/'),
    (86, 'Graphs', 11, 'Walls And Gates', 'MEDIUM', 'https://leetcode.com/problems/walls-and-gates/'),
    (87, 'Graphs', 11, 'Course Schedule', 'MEDIUM', 'https://leetcode.com/problems/course-schedule/'),
    (88, 'Graphs', 11, 'Course Schedule II', 'MEDIUM', 'https://leetcode.com/problems/course-schedule-ii/'),
    (89, 'Graphs', 11, 'Redundant Connection', 'MEDIUM', 'https://leetcode.com/problems/redundant-connection/'),
    (90, 'Graphs', 11, 'Number of Connected Components In An Undirected Graph', 'MEDIUM', 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/'),
    (91, 'Graphs', 11, 'Graph Valid Tree', 'MEDIUM', 'https://leetcode.com/problems/graph-valid-tree/'),
    (92, 'Graphs', 11, 'Word Ladder', 'HARD', 'https://leetcode.com/problems/word-ladder/'),
    (93, 'Advanced Graphs', 12, 'Reconstruct Itinerary', 'HARD', 'https://leetcode.com/problems/reconstruct-itinerary/'),
    (94, 'Advanced Graphs', 12, 'Min Cost to Connect All Points', 'MEDIUM', 'https://leetcode.com/problems/min-cost-to-connect-all-points/'),
    (95, 'Advanced Graphs', 12, 'Network Delay Time', 'MEDIUM', 'https://leetcode.com/problems/network-delay-time/'),
    (96, 'Advanced Graphs', 12, 'Swim In Rising Water', 'HARD', 'https://leetcode.com/problems/swim-in-rising-water/'),
    (97, 'Advanced Graphs', 12, 'Alien Dictionary', 'HARD', 'https://leetcode.com/problems/alien-dictionary/'),
    (98, 'Advanced Graphs', 12, 'Cheapest Flights Within K Stops', 'MEDIUM', 'https://leetcode.com/problems/cheapest-flights-within-k-stops/'),
    (99, '1-D Dynamic Programming', 13, 'Climbing Stairs', 'EASY', 'https://leetcode.com/problems/climbing-stairs/'),
    (100, '1-D Dynamic Programming', 13, 'Min Cost Climbing Stairs', 'EASY', 'https://leetcode.com/problems/min-cost-climbing-stairs/'),
    (101, '1-D Dynamic Programming', 13, 'House Robber', 'MEDIUM', 'https://leetcode.com/problems/house-robber/'),
    (102, '1-D Dynamic Programming', 13, 'House Robber II', 'MEDIUM', 'https://leetcode.com/problems/house-robber-ii/'),
    (103, '1-D Dynamic Programming', 13, 'Longest Palindromic Substring', 'MEDIUM', 'https://leetcode.com/problems/longest-palindromic-substring/'),
    (104, '1-D Dynamic Programming', 13, 'Palindromic Substrings', 'MEDIUM', 'https://leetcode.com/problems/palindromic-substrings/'),
    (105, '1-D Dynamic Programming', 13, 'Decode Ways', 'MEDIUM', 'https://leetcode.com/problems/decode-ways/'),
    (106, '1-D Dynamic Programming', 13, 'Coin Change', 'MEDIUM', 'https://leetcode.com/problems/coin-change/'),
    (107, '1-D Dynamic Programming', 13, 'Maximum Product Subarray', 'MEDIUM', 'https://leetcode.com/problems/maximum-product-subarray/'),
    (108, '1-D Dynamic Programming', 13, 'Word Break', 'MEDIUM', 'https://leetcode.com/problems/word-break/'),
    (109, '1-D Dynamic Programming', 13, 'Longest Increasing Subsequence', 'MEDIUM', 'https://leetcode.com/problems/longest-increasing-subsequence/'),
    (110, '1-D Dynamic Programming', 13, 'Partition Equal Subset Sum', 'MEDIUM', 'https://leetcode.com/problems/partition-equal-subset-sum/'),
    (111, '2-D Dynamic Programming', 14, 'Unique Paths', 'MEDIUM', 'https://leetcode.com/problems/unique-paths/'),
    (112, '2-D Dynamic Programming', 14, 'Longest Common Subsequence', 'MEDIUM', 'https://leetcode.com/problems/longest-common-subsequence/'),
    (113, '2-D Dynamic Programming', 14, 'Best Time to Buy And Sell Stock With Cooldown', 'MEDIUM', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/'),
    (114, '2-D Dynamic Programming', 14, 'Coin Change II', 'MEDIUM', 'https://leetcode.com/problems/coin-change-ii/'),
    (115, '2-D Dynamic Programming', 14, 'Target Sum', 'MEDIUM', 'https://leetcode.com/problems/target-sum/'),
    (116, '2-D Dynamic Programming', 14, 'Interleaving String', 'MEDIUM', 'https://leetcode.com/problems/interleaving-string/'),
    (117, '2-D Dynamic Programming', 14, 'Longest Increasing Path In a Matrix', 'HARD', 'https://leetcode.com/problems/longest-increasing-path-in-a-matrix/'),
    (118, '2-D Dynamic Programming', 14, 'Distinct Subsequences', 'HARD', 'https://leetcode.com/problems/distinct-subsequences/'),
    (119, '2-D Dynamic Programming', 14, 'Edit Distance', 'MEDIUM', 'https://leetcode.com/problems/edit-distance/'),
    (120, '2-D Dynamic Programming', 14, 'Burst Balloons', 'HARD', 'https://leetcode.com/problems/burst-balloons/'),
    (121, '2-D Dynamic Programming', 14, 'Regular Expression Matching', 'HARD', 'https://leetcode.com/problems/regular-expression-matching/'),
    (122, 'Greedy', 15, 'Maximum Subarray', 'MEDIUM', 'https://leetcode.com/problems/maximum-subarray/'),
    (123, 'Greedy', 15, 'Jump Game', 'MEDIUM', 'https://leetcode.com/problems/jump-game/'),
    (124, 'Greedy', 15, 'Jump Game II', 'MEDIUM', 'https://leetcode.com/problems/jump-game-ii/'),
    (125, 'Greedy', 15, 'Gas Station', 'MEDIUM', 'https://leetcode.com/problems/gas-station/'),
    (126, 'Greedy', 15, 'Hand of Straights', 'MEDIUM', 'https://leetcode.com/problems/hand-of-straights/'),
    (127, 'Greedy', 15, 'Merge Triplets to Form Target Triplet', 'MEDIUM', 'https://leetcode.com/problems/merge-triplets-to-form-target-triplet/'),
    (128, 'Greedy', 15, 'Partition Labels', 'MEDIUM', 'https://leetcode.com/problems/partition-labels/'),
    (129, 'Greedy', 15, 'Valid Parenthesis String', 'MEDIUM', 'https://leetcode.com/problems/valid-parenthesis-string/'),
    (130, 'Intervals', 16, 'Insert Interval', 'MEDIUM', 'https://leetcode.com/problems/insert-interval/'),
    (131, 'Intervals', 16, 'Merge Intervals', 'MEDIUM', 'https://leetcode.com/problems/merge-intervals/'),
    (132, 'Intervals', 16, 'Non Overlapping Intervals', 'MEDIUM', 'https://leetcode.com/problems/non-overlapping-intervals/'),
    (133, 'Intervals', 16, 'Meeting Rooms', 'EASY', 'https://leetcode.com/problems/meeting-rooms/'),
    (134, 'Intervals', 16, 'Meeting Rooms II', 'MEDIUM', 'https://leetcode.com/problems/meeting-rooms-ii/'),
    (135, 'Intervals', 16, 'Minimum Interval to Include Each Query', 'HARD', 'https://leetcode.com/problems/minimum-interval-to-include-each-query/'),
    (136, 'Math & Geometry', 17, 'Rotate Image', 'MEDIUM', 'https://leetcode.com/problems/rotate-image/'),
    (137, 'Math & Geometry', 17, 'Spiral Matrix', 'MEDIUM', 'https://leetcode.com/problems/spiral-matrix/'),
    (138, 'Math & Geometry', 17, 'Set Matrix Zeroes', 'MEDIUM', 'https://leetcode.com/problems/set-matrix-zeroes/'),
    (139, 'Math & Geometry', 17, 'Happy Number', 'EASY', 'https://leetcode.com/problems/happy-number/'),
    (140, 'Math & Geometry', 17, 'Plus One', 'EASY', 'https://leetcode.com/problems/plus-one/'),
    (141, 'Math & Geometry', 17, 'Pow(x, n)', 'MEDIUM', 'https://leetcode.com/problems/powx-n/'),
    (142, 'Math & Geometry', 17, 'Multiply Strings', 'MEDIUM', 'https://leetcode.com/problems/multiply-strings/'),
    (143, 'Math & Geometry', 17, 'Detect Squares', 'MEDIUM', 'https://leetcode.com/problems/detect-squares/'),
    (144, 'Bit Manipulation', 18, 'Single Number', 'EASY', 'https://leetcode.com/problems/single-number/'),
    (145, 'Bit Manipulation', 18, 'Number of 1 Bits', 'EASY', 'https://leetcode.com/problems/number-of-1-bits/'),
    (146, 'Bit Manipulation', 18, 'Counting Bits', 'EASY', 'https://leetcode.com/problems/counting-bits/'),
    (147, 'Bit Manipulation', 18, 'Reverse Bits', 'EASY', 'https://leetcode.com/problems/reverse-bits/'),
    (148, 'Bit Manipulation', 18, 'Missing Number', 'EASY', 'https://leetcode.com/problems/missing-number/'),
    (149, 'Bit Manipulation', 18, 'Sum of Two Integers', 'MEDIUM', 'https://leetcode.com/problems/sum-of-two-integers/'),
    (150, 'Bit Manipulation', 18, 'Reverse Integer', 'MEDIUM', 'https://leetcode.com/problems/reverse-integer/');

-- Each catalog problem can be marked done at most once.
ALTER TABLE problems ADD COLUMN catalog_id SMALLINT REFERENCES catalog_problems (id);
CREATE UNIQUE INDEX problems_catalog_unique ON problems (catalog_id) WHERE catalog_id IS NOT NULL;

-- Link problems you logged by hand earlier when the name matches a NeetCode problem.
-- Anything that doesn't match keeps catalog_id = NULL and shows as an "earlier entry".
UPDATE problems p
SET catalog_id = c.id
FROM catalog_problems c
WHERE lower(p.name) = lower(c.name);

-- "Method used" becomes "What did you learn?".
ALTER TABLE problems RENAME COLUMN method TO learnings;
ALTER TABLE problems RENAME CONSTRAINT problems_method_not_blank TO problems_learnings_not_blank;

-- The "solved it yourself?" question is gone; old answers are kept.
ALTER TABLE problems ALTER COLUMN solved_myself DROP NOT NULL;

-- Optional link to your Excalidraw drawing for the problem.
ALTER TABLE problems ADD COLUMN excalidraw_url VARCHAR(500);
